### ISSUE TITLE
580611013 Class Player in OXPlugin should validate username before create

### ISSUE THREAD

**Issue by commee67** [ISNE360260/DNWS#1]
It has duplicate players when we create player with same username. So, class Player should validate username before create with encapsulation for controlling data.

<img width="204" alt="screen shot 2561-02-14 at 04 45 50" src="https://user-images.githubusercontent.com/21051232/36175429-fceb1372-1141-11e8-9dff-2b257aa3469e.png">

Encapsulation Using .NET Properties
Ex.
```
    public class Player
    {
        ...
        protected String _name;
        public String Name
        {
            get { return _name; }   
            set {
                if (name is in list){
                    show "This username has in list already"
                }
                else{
                    _name = name
                }    
            }
        }
    }
```

**Comment by pruet** [comment]
1. Any better way to emit the error beside showing the message?  Look at AddPlayer() method, if the player exists, this method should fail as well.
2. What kind of list? Now, we use _playerList, but it's out side of Player class scope, should we reimplement the Player class in the other way? or any suggestion?

**Comment by chaloempong** [comment]
1. Fortunately, in your code has GetPlayerByUserName method. So, I can use it for checking username in _playerList before create and show error in create new page. 
<img width="902" alt="screen shot 2561-02-15 at 20 53 48" src="https://user-images.githubusercontent.com/21051232/36261770-0c297854-1298-11e8-90bb-bd91329aefcc.png">
<img width="573" alt="screen shot 2561-02-15 at 21 37 44" src="https://user-images.githubusercontent.com/21051232/36261913-7f27db98-1298-11e8-959a-57abff4edde1.png">

2. Now, _playerList is protected member of OXGame class. And I think _playerList should be in OXGame class because I feel... It is the one of attribute of OXGame class not Player class. 

3. I wonder why AddPlayer method have to return int(index) instead of return void.
